import USDTLOGO from '../../../assets/roundedlogo.svg';

export const arr = [
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
        imported:true
    },
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
    },
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
        imported:true
    },
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
        imported:true
    },
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
    },
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
        imported:true
    },
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
        imported:true
    },
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
    },
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
        imported:true
    },
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
        imported:true
    },
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
    },
    {
        symbol:"RGP",
        name:"RigelCoin",
        balance:"4.5554",
        img:USDTLOGO,
        imported:true
    },
]